{{- if .Values.litellm.enabled }}
{{- $secretName := include "openclaw.litellm.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "openclaw.litellm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- /* apiKey */}}
  {{- if .Values.litellm.secrets.apiKey }}
  apiKey: {{ .Values.litellm.secrets.apiKey | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  apiKey: {{ index $existingSecret.data "apiKey" | default "" | quote }}
  {{- else }}
  apiKey: ""
  {{- end }}

  {{- /* apiBase */}}
  {{- if .Values.litellm.secrets.apiBase }}
  apiBase: {{ .Values.litellm.secrets.apiBase | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  apiBase: {{ index $existingSecret.data "apiBase" | default "" | quote }}
  {{- else }}
  apiBase: ""
  {{- end }}
{{- end }}
