{{- if not .Values.secrets.existingSecret -}}
{{/*
  Use lookup function to preserve existing secrets on upgrade.
  This prevents regenerating tokens and API keys when the chart is upgraded.
*/}}
{{- $secretName := include "openclaw.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- /* DISCORD_BOT_TOKEN */}}
  {{- if .Values.secrets.discordBotToken }}
  DISCORD_BOT_TOKEN: {{ .Values.secrets.discordBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  DISCORD_BOT_TOKEN: {{ index $existingSecret.data "DISCORD_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  DISCORD_BOT_TOKEN: ""
  {{- end }}

  {{- /* TELEGRAM_BOT_TOKEN */}}
  {{- if .Values.secrets.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  TELEGRAM_BOT_TOKEN: {{ index $existingSecret.data "TELEGRAM_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  TELEGRAM_BOT_TOKEN: ""
  {{- end }}

  {{- /* SLACK_BOT_TOKEN */}}
  {{- if .Values.secrets.slackBotToken }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  SLACK_BOT_TOKEN: {{ index $existingSecret.data "SLACK_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  SLACK_BOT_TOKEN: ""
  {{- end }}

  {{- /* SLACK_APP_TOKEN */}}
  {{- if .Values.secrets.slackAppToken }}
  SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  SLACK_APP_TOKEN: {{ index $existingSecret.data "SLACK_APP_TOKEN" | default "" | quote }}
  {{- else }}
  SLACK_APP_TOKEN: ""
  {{- end }}

  {{- /* FEISHU_APP_ID */}}
  {{- if .Values.secrets.feishuAppId }}
  FEISHU_APP_ID: {{ .Values.secrets.feishuAppId | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  FEISHU_APP_ID: {{ index $existingSecret.data "FEISHU_APP_ID" | default "" | quote }}
  {{- else }}
  FEISHU_APP_ID: ""
  {{- end }}

  {{- /* FEISHU_APP_SECRET */}}
  {{- if .Values.secrets.feishuAppSecret }}
  FEISHU_APP_SECRET: {{ .Values.secrets.feishuAppSecret | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  FEISHU_APP_SECRET: {{ index $existingSecret.data "FEISHU_APP_SECRET" | default "" | quote }}
  {{- else }}
  FEISHU_APP_SECRET: ""
  {{- end }}

  {{- /* MSTEAMS_APP_ID */}}
  {{- if .Values.secrets.msteamsAppId }}
  MSTEAMS_APP_ID: {{ .Values.secrets.msteamsAppId | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  MSTEAMS_APP_ID: {{ index $existingSecret.data "MSTEAMS_APP_ID" | default "" | quote }}
  {{- else }}
  MSTEAMS_APP_ID: ""
  {{- end }}

  {{- /* MSTEAMS_APP_PASSWORD */}}
  {{- if .Values.secrets.msteamsAppPassword }}
  MSTEAMS_APP_PASSWORD: {{ .Values.secrets.msteamsAppPassword | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  MSTEAMS_APP_PASSWORD: {{ index $existingSecret.data "MSTEAMS_APP_PASSWORD" | default "" | quote }}
  {{- else }}
  MSTEAMS_APP_PASSWORD: ""
  {{- end }}

  {{- /* MSTEAMS_TENANT_ID */}}
  {{- if .Values.secrets.msteamsTenantId }}
  MSTEAMS_TENANT_ID: {{ .Values.secrets.msteamsTenantId | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  MSTEAMS_TENANT_ID: {{ index $existingSecret.data "MSTEAMS_TENANT_ID" | default "" | quote }}
  {{- else }}
  MSTEAMS_TENANT_ID: ""
  {{- end }}

  {{- /* BRAVE_API_KEY */}}
  {{- if .Values.secrets.braveApiKey }}
  BRAVE_API_KEY: {{ .Values.secrets.braveApiKey | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  BRAVE_API_KEY: {{ index $existingSecret.data "BRAVE_API_KEY" | default "" | quote }}
  {{- else }}
  BRAVE_API_KEY: ""
  {{- end }}

  {{- /* PERPLEXITY_API_KEY */}}
  {{- if .Values.secrets.perplexityApiKey }}
  PERPLEXITY_API_KEY: {{ .Values.secrets.perplexityApiKey | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  PERPLEXITY_API_KEY: {{ index $existingSecret.data "PERPLEXITY_API_KEY" | default "" | quote }}
  {{- else }}
  PERPLEXITY_API_KEY: ""
  {{- end }}

  {{- /* OPENCLAW_GATEWAY_TOKEN - Required, but use placeholder for linting */}}
  {{- if .Values.secrets.openclawGatewayToken }}
  OPENCLAW_GATEWAY_TOKEN: {{ .Values.secrets.openclawGatewayToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  OPENCLAW_GATEWAY_TOKEN: {{ index $existingSecret.data "OPENCLAW_GATEWAY_TOKEN" | default "" | quote }}
  {{- else }}
  # Placeholder for initial deployment - should be replaced with actual value
  OPENCLAW_GATEWAY_TOKEN: {{ "change-me" | b64enc | quote }}
  {{- end }}
{{- end }}
