{{- if not .Values.secrets.existingSecret -}}
{{/*
  Use lookup function to preserve existing secrets on upgrade.
  This prevents regenerating tokens and API keys when the chart is upgraded.
*/}}
{{- $secretName := include "openclaw.secretName" . -}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- with .Values.secrets.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- /* DISCORD_BOT_TOKEN */}}
  {{- if .Values.secrets.discordBotToken }}
  DISCORD_BOT_TOKEN: {{ .Values.secrets.discordBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  DISCORD_BOT_TOKEN: {{ index $existingSecret.data "DISCORD_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  DISCORD_BOT_TOKEN: ""
  {{- end }}

  {{- /* TELEGRAM_BOT_TOKEN */}}
  {{- if .Values.secrets.telegramBotToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.secrets.telegramBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  TELEGRAM_BOT_TOKEN: {{ index $existingSecret.data "TELEGRAM_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  TELEGRAM_BOT_TOKEN: ""
  {{- end }}

  {{- /* SLACK_BOT_TOKEN */}}
  {{- if .Values.secrets.slackBotToken }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.slackBotToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  SLACK_BOT_TOKEN: {{ index $existingSecret.data "SLACK_BOT_TOKEN" | default "" | quote }}
  {{- else }}
  SLACK_BOT_TOKEN: ""
  {{- end }}

  {{- /* SLACK_APP_TOKEN */}}
  {{- if .Values.secrets.slackAppToken }}
  SLACK_APP_TOKEN: {{ .Values.secrets.slackAppToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  SLACK_APP_TOKEN: {{ index $existingSecret.data "SLACK_APP_TOKEN" | default "" | quote }}
  {{- else }}
  SLACK_APP_TOKEN: ""
  {{- end }}

  {{- /* OPENCLAW_GATEWAY_TOKEN - Required, but use placeholder for linting */}}
  {{- if .Values.secrets.openclawGatewayToken }}
  OPENCLAW_GATEWAY_TOKEN: {{ .Values.secrets.openclawGatewayToken | b64enc | quote }}
  {{- else if and $existingSecret $existingSecret.data }}
  OPENCLAW_GATEWAY_TOKEN: {{ index $existingSecret.data "OPENCLAW_GATEWAY_TOKEN" | default "" | quote }}
  {{- else }}
  # Placeholder for initial deployment - should be replaced with actual value
  OPENCLAW_GATEWAY_TOKEN: {{ "change-me" | b64enc | quote }}
  {{- end }}
{{- end }}
